const seed=[
['RDM001','REHAN AKHTAR','CAPTAIN • ALL-ROUNDER','RIGHT-HANDED • RIGHT-ARM FAST • MIDDLE ORDER • MIDDLE OVERS','','assets/rehan.png','08'],['RDM002','ASIF ALI','BATSMAN','RIGHT-HANDED • TOP ORDER','','assets/logo.jpg',''],['RDM003','SAIF ALI','VICE-CAPTAIN • ALL-ROUNDER','BOTH-HANDED • FAST • NON-STRIKER OPENER • ALL PHASES','','assets/logo.jpg',''],['RDM004','AKIB ANSARI','ALL-ROUNDER','RIGHT-HANDED • FAST • STRIKER OPENER • MIDDLE + DEATH','','assets/logo.jpg',''],['RDM005','SAHIL ALI','BATSMAN','RIGHT-HANDED • MIDDLE ORDER • FINISHER','','assets/logo.jpg',''],['RDM006','SOAIB AKHTAR','WICKET-KEEPER • BATSMAN','RIGHT-HANDED • LEFT-ARM FAST • TOP ORDER • FINISHER','','assets/logo.jpg',''],['RDM007','WASIM','ALL-ROUNDER','RIGHT-HANDED • FAST • TOP ORDER • ALL PHASES','','assets/logo.jpg',''],['RDM008','JUBED','BATSMAN','RIGHT-HANDED • MIDDLE ORDER','','assets/logo.jpg',''],['RDM009','SHEIKH HANIF','BATSMAN','RIGHT-HANDED • FINISHER','','assets/logo.jpg',''],['RDM010','GULAM','ALL-ROUNDER','RIGHT-HANDED • FAST • FINISHER • EMERGENCY BOWLING','','assets/logo.jpg',''],['RDM011','ANISH','ALL-ROUNDER','RIGHT-HANDED • FAST • TOP ORDER • ALL PHASES','','assets/logo.jpg',''],['RDM012','LUCKY','SUBSTITUTE • ALL-ROUNDER','RIGHT-HANDED • FAST • MIDDLE ORDER • MIDDLE OVERS','','assets/logo.jpg',''],['RDM013','ABUSHAD','SUBSTITUTE • ALL-ROUNDER','RIGHT-HANDED • FAST • MIDDLE ORDER + FINISHER • MIDDLE + DEATH','','assets/logo.jpg',''],['RDM014','SABRE ALAM','SUBSTITUTE • BATSMAN','RIGHT-HANDED • FINISHER','','assets/logo.jpg',''],['RDM015','ZISHAN','SUBSTITUTE • BATSMAN','RIGHT-HANDED • FINISHER','','assets/logo.jpg','']];
const playerDefaults={"RDM001": {"nick": "THE SKIPPER", "bio": "CAPTAIN AND ALL-ROUNDER WHO LEADS FROM THE FRONT WITH DISCIPLINE, CONFIDENCE AND TEAM-FIRST CRICKET."}, "RDM002": {"nick": "THE ANCHOR", "bio": "A RELIABLE TOP-ORDER BATSMAN WHO VALUES A SOLID START, SMART SHOT SELECTION AND STEADY RUNS."}, "RDM003": {"nick": "THE GAME CHANGER", "bio": "VICE-CAPTAIN AND ALL-ROUNDER WHO BRINGS FLEXIBILITY, ENERGY AND IMPACT THROUGH EVERY PHASE OF THE GAME."}, "RDM004": {"nick": "THE ATTACKER", "bio": "AN AGGRESSIVE STRIKE OPENER AND FAST-BOWLING ALL-ROUNDER BUILT TO SET THE TEMPO AND DELIVER UNDER PRESSURE."}, "RDM005": {"nick": "THE FINISHER", "bio": "A CALM MIDDLE-ORDER BATSMAN WHO BACKS HIS SHOTS AND LOOKS TO FINISH INNINGS WITH CONFIDENCE."}, "RDM006": {"nick": "THE GLOVEMAN", "bio": "THE TEAM’S MAIN WICKET-KEEPER AND A VERSATILE BATSMAN WHO ADDS ENERGY, AWARENESS AND BALANCE TO THE XI."}, "RDM007": {"nick": "THE COMPLETE PACKAGE", "bio": "A TOP-ORDER ALL-ROUNDER WHO CAN CONTRIBUTE WITH BAT AND BALL ACROSS EVERY PHASE OF THE MATCH."}, "RDM008": {"nick": "THE MIDDLE ROCK", "bio": "A DEPENDABLE MIDDLE-ORDER BATSMAN FOCUSED ON BUILDING PARTNERSHIPS AND KEEPING THE INNINGS MOVING."}, "RDM009": {"nick": "THE CLOSER", "bio": "A FINISHER WHO ENJOYS THE PRESSURE MOMENTS AND LOOKS TO GIVE THE TEAM A STRONG END TO THE INNINGS."}, "RDM010": {"nick": "THE IMPACT PLAYER", "bio": "A USEFUL ALL-ROUNDER AND FINISHER WHO CAN CHANGE MOMENTUM WITH QUICK RUNS AND EMERGENCY BOWLING."}, "RDM011": {"nick": "THE ALL-PHASE ACE", "bio": "A TOP-ORDER ALL-ROUNDER WITH THE ABILITY TO CONTRIBUTE THROUGHOUT THE INNINGS AND BOWL IN ANY PHASE."}, "RDM012": {"nick": "THE READY RESERVE", "bio": "A VERSATILE SUBSTITUTE ALL-ROUNDER WHO STAYS READY TO CONTRIBUTE WITH BAT OR BALL WHEN THE TEAM NEEDS HIM."}, "RDM013": {"nick": "THE UTILITY ACE", "bio": "A FLEXIBLE SUBSTITUTE ALL-ROUNDER WHO CAN FINISH WITH THE BAT AND HANDLE IMPORTANT MIDDLE OR DEATH OVERS."}, "RDM014": {"nick": "THE POWER FINISHER", "bio": "A SUBSTITUTE BATSMAN WITH A FINISHER’S ROLE, READY TO ADD QUICK RUNS AND IMPACT WHEN CALLED UPON."}, "RDM015": {"nick": "THE LAST-OVER HITTER", "bio": "A SUBSTITUTE FINISHER WHO PLAYS WITH INTENT AND STAYS READY FOR HIGH-PRESSURE BATTING OPPORTUNITIES."}};
const K='RDM_V33_DATA',SK='RDM_V33_SESSION';
const fresh=()=>({players:seed.map(x=>({id:x[0],name:x[1],role:x[2],detail:x[3],pass:x[4],image:x[5],jersey:x[6],nick:(playerDefaults[x[0]]?.nick||''),bio:(playerDefaults[x[0]]?.bio||''),socials:[]})),matches:[],news:[],gallery:[],honours:[{year:'2024',title:'WINNER',sub:'MAHUAWAN PREMIER LEAGUE 1',image:'assets/trophy-2024.png'},{year:'2025',title:'WINNER',sub:'MAHUAWAN PREMIER LEAGUE 2',image:'assets/trophy-2025.png'},{year:'2026',title:'RUNNER-UP',sub:'TOURNAMENT NAME • TO BE ADDED',image:'assets/trophy-2026.png'}],socials:[{name:'INSTAGRAM',url:'',icon:'IG',image:''},{name:'FACEBOOK',url:'',icon:'f',image:''},{name:'YOUTUBE',url:'https://www.youtube.com/@rehan_dominators_mahuawan',icon:'▶',image:''},{name:'TELEGRAM',url:'',icon:'✈',image:''},{name:'WHATSAPP',url:'https://wa.me/918521254605',icon:'◉',image:''}]});
let D;try{D=JSON.parse(localStorage.getItem(K))||fresh()}catch{D=fresh()}
// Repair incomplete/blank saved data automatically
if(!D||!Array.isArray(D.players)||D.players.length===0){D=fresh();saveLater=true}else{var saveLater=false}
if(!Array.isArray(D.honours)||D.honours.length===0)D.honours=fresh().honours;
if(!Array.isArray(D.socials)||D.socials.length===0)D.socials=fresh().socials;
const requiredSocials=fresh().socials;requiredSocials.forEach(def=>{let found=D.socials.find(x=>String((Array.isArray(x)?x[0]:x.name)||'').toUpperCase().includes(def.name));if(!found)D.socials.push({...def});else if(!Array.isArray(found)){if(found.image===undefined)found.image='';if(!found.icon)found.icon=def.icon;}});
D.players.forEach(p=>{const d=playerDefaults[p.id];if(d){if(!p.nick)p.nick=d.nick;if(!p.bio)p.bio=d.bio;}});if(!Array.isArray(D.matches))D.matches=[];if(!Array.isArray(D.news))D.news=[];if(!Array.isArray(D.gallery))D.gallery=[];let session=null;try{session=JSON.parse(localStorage.getItem(SK))}catch{}let loginMode='player',editMode='',editObj=null;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],save=()=>localStorage.setItem(K,JSON.stringify(D));
function mini(s=''){const m={A:'ᴀ',B:'ʙ',C:'ᴄ',D:'ᴅ',E:'ᴇ',F:'ꜰ',G:'ɢ',H:'ʜ',I:'ɪ',J:'ᴊ',K:'ᴋ',L:'ʟ',M:'ᴍ',N:'ɴ',O:'ᴏ',P:'ᴘ',Q:'ǫ',R:'ʀ',S:'ꜱ',T:'ᴛ',U:'ᴜ',V:'ᴠ',W:'ᴡ',X:'x',Y:'ʏ',Z:'ᴢ'};return String(s).toUpperCase().split('').map(c=>m[c]||c).join('')}
function miniId(s=''){return mini(s)}function toast(t){let x=q('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)}
function go(id){if((id==='profile'&&session?.mode!=='player')||(id==='admin'&&session?.mode!=='admin'))return;qa('.page').forEach(x=>x.classList.toggle('active',x.id===id));qa('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='profile')renderProfile();if(id==='admin')renderAdmin();scrollTo({top:0,behavior:'smooth'})}
qa('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));qa('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function isAdmin(){return session?.mode==='admin'}function currentPlayer(){return D.players.find(p=>p.id===session?.playerId)}
function updateAuthUI(){document.body.classList.toggle('admin',isAdmin());q('#profileNav').hidden=session?.mode!=='player';q('#adminNav').hidden=!isAdmin();q('#loginOpen').textContent=session?'ʟᴏɢᴏᴜᴛ':'ʟᴏɢɪɴ';q('#switchBtn').hidden=!session?.canSwitch;q('#switchBtn').textContent=session?.mode==='admin'?'⇄ ʀᴇʜᴀɴ':'⇄ ᴀᴅᴍɪɴ'}
function render(){q('#players').innerHTML=D.players.map(p=>`<article class="player"><div class="photo"><img src="${p.image||'assets/logo.jpg'}" alt="${p.name}"></div><div class="pbody"><span class="badge">${miniId(p.id)}${p.jersey?' • #'+p.jersey:''}</span><h3>${mini(p.name)}</h3><b>${mini(p.role)}</b><p>${mini(p.detail)}</p>${p.nick?`<p>ɴɪᴄᴋɴᴀᴍᴇ • ${mini(p.nick)}</p>`:''}<button class="tinyBtn adminOnly" onclick="editPlayer('${p.id}')">✎ ᴇᴅɪᴛ</button></div></article>`).join('');
q('#honourList').innerHTML=D.honours.map((h,i)=>`<article class="honour"><div class="trophy"><img src="${h.image}" onclick="zoom('${h.image}')"></div><h3>${h.year} • ${mini(h.title)}</h3><p>${mini(h.sub)}</p>${isAdmin()?`<button class="tinyBtn" onclick="removeItem('honours',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join('');
q('#matchList').innerHTML=D.matches.length?D.matches.map((m,i)=>`<article class="card"><h3>${mini(m.opponent)}</h3><p>${mini(m.date)} • ${mini(m.venue)}</p><p>${mini(m.note)}</p>${isAdmin()?`<button class="tinyBtn" onclick="removeItem('matches',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴍᴀᴛᴄʜ ᴀᴅᴅᴇᴅ ʏᴇᴛ</div>';
q('#newsList').innerHTML=D.news.length?D.news.map((n,i)=>`<article class="card"><h3>${mini(n.title)}</h3><p>${mini(n.text)}</p>${isAdmin()?`<button class="tinyBtn" onclick="removeItem('news',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ ʏᴇᴛ</div>';
q('#galleryList').innerHTML=D.gallery.length?D.gallery.map((g,i)=>`<figure><img src="${g.image}" onclick="zoom('${g.image}')"><figcaption>${mini(g.caption||'RDM MEMORY')}</figcaption>${isAdmin()?`<button class="tinyBtn" onclick="removeItem('gallery',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</figure>`).join(''):'<div class="empty">ɴᴏ ɢᴀʟʟᴇʀʏ ᴘʜᴏᴛᴏ ᴀᴅᴅᴇᴅ ʏᴇᴛ</div>';
q('#socialList').innerHTML=D.socials.map((s,i)=>{let o=Array.isArray(s)?{name:s[0],url:s[1],icon:'↗',image:''}:s;let media=o.image?`<img src="${o.image}" alt="${o.name}">`:`<span>${o.icon||'↗'}</span>`;let open=o.url?`<a class="primary socialAction" href="${o.url}" target="_blank">ᴏᴘᴇɴ</a>`:`<button class="secondary socialAction" disabled>ʟɪɴᴋ ɴᴏᴛ ᴀᴅᴅᴇᴅ</button>`;return `<article class="socialCard"><div class="socialIcon">${media}</div><h3>${mini(o.name)}</h3><div class="socialActions">${open}${isAdmin()?`<button class="tinyBtn socialAction" onclick="editSocial(${i})">✎ ᴇᴅɪᴛ</button>`:''}</div></article>`}).join('');updateAuthUI()}
window.removeItem=(k,i)=>{if(!isAdmin())return;D[k].splice(i,1);save();render();toast('ᴅᴇʟᴇᴛᴇᴅ')};window.zoom=src=>{q('#lightImg').src=src;q('#lightbox').classList.add('show')};qa('.modal .close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('show'));
q('#loginOpen').onclick=()=>{if(session){localStorage.removeItem(SK);session=null;updateAuthUI();render();go('home');toast('ʟᴏɢɢᴇᴅ ᴏᴜᴛ')}else q('#loginModal').classList.add('show')};
qa('[data-login]').forEach(b=>b.onclick=()=>{loginMode=b.dataset.login;qa('[data-login]').forEach(x=>x.classList.toggle('on',x===b));q('#playerFields').hidden=loginMode!=='player';q('#adminFields').hidden=loginMode!=='admin';q('#loginError').textContent=''});
q('#loginForm').onsubmit=e=>{e.preventDefault();let pass=q('#password').value.trim(),ok=false;if(loginMode==='admin'){let mob=q('#amobile').value.replace(/\D/g,'');if(mob==='8521254605'&&pass.toUpperCase()==='__FIREBASE_ONLY__'){session={mode:'admin',canSwitch:true,playerId:'RDM001'};ok=true}}else{let name=q('#pname').value.trim().toUpperCase(),id=q('#pid').value.trim().toUpperCase(),p=D.players.find(x=>x.name.toUpperCase()===name&&x.id===id&&x.pass===pass);if(p){session={mode:'player',playerId:p.id,canSwitch:p.id==='RDM001'};ok=true}}if(!ok){q('#loginError').textContent='ʟᴏɢɪɴ ᴅᴇᴛᴀɪʟꜱ ᴅᴏ ɴᴏᴛ ᴍᴀᴛᴄʜ';return}if(q('#remember').checked)localStorage.setItem(SK,JSON.stringify(session));else localStorage.removeItem(SK);q('#loginModal').classList.remove('show');q('#loginForm').reset();render();go(session.mode==='admin'?'admin':'profile');toast('ʟᴏɢɪɴ ꜱᴜᴄᴄᴇꜱꜱꜰᴜʟ')};
q('#switchBtn').onclick=()=>{if(!session?.canSwitch)return;session.mode=session.mode==='admin'?'player':'admin';localStorage.setItem(SK,JSON.stringify(session));render();go(session.mode==='admin'?'admin':'profile');toast(session.mode==='admin'?'ᴀᴅᴍɪɴ ᴍᴏᴅᴇ':'ʀᴇʜᴀɴ ᴘʀᴏꜰɪʟᴇ')};
function renderProfile(){let p=currentPlayer();if(!p)return;let socials=p.socials?.length?`<div class="ownSocials">${p.socials.map((x,i)=>`<a href="${x}" target="_blank">ꜱᴏᴄɪᴀʟ ${i+1} ↗</a>`).join('')}</div>`:'';q('#profileBody').innerHTML=`<article class="profileCard"><img class="profileAvatar" src="${p.image}"><h2>${mini(p.name)}</h2><div class="profileIdentity"><div class="identityItem"><span>ᴘʟᴀʏᴇʀ ɪᴅ</span><strong>${miniId(p.id)}</strong></div><div class="identityDivider"></div><div class="identityItem"><span>ᴊᴇʀꜱᴇʏ ɴᴜᴍʙᴇʀ</span><strong>${p.jersey?'#'+p.jersey:'—'}</strong></div></div>${p.nick?`<p>${mini(p.nick)}</p>`:''}<div class="profileOfficial"><b>${mini(p.role)}</b><br>${mini(p.detail)}<div class="officialLock">🔒 ᴏꜰꜰɪᴄɪᴀʟ ᴛᴇᴀᴍ ᴅᴀᴛᴀ • ᴀᴅᴍɪɴ ᴏɴʟʏ</div></div>${p.bio?`<p>${mini(p.bio)}</p>`:''}${socials}<div class="profileActions"><button class="secondary" onclick="chooseDP()">✎ ᴘʜᴏᴛᴏ</button><button class="secondary" onclick="selfEdit('jersey')">✎ ᴊᴇʀꜱᴇʏ</button><button class="secondary" onclick="selfEdit('nick')">✎ ɴɪᴄᴋɴᴀᴍᴇ</button><button class="secondary" onclick="selfEdit('bio')">✎ ʙɪᴏ</button><button class="secondary" onclick="selfEdit('socials')">✎ ꜱᴏᴄɪᴀʟꜱ</button><button class="secondary" onclick="selfEdit('pass')">🔐 ᴘᴀꜱꜱᴡᴏʀᴅ</button></div></article>`}
window.selfEdit=k=>{let p=currentPlayer();if(!p)return;let label={jersey:'JERSEY NUMBER',nick:'NICKNAME',bio:'BIO',socials:'MAX 3 SOCIAL LINKS • COMMA SEPARATED',pass:'NEW PASSWORD'}[k],old=k==='socials'?(p.socials||[]).join(', '):k==='pass'?'':p[k]||'',v=prompt(label,old);if(v===null)return;if(k==='socials')p.socials=v.split(',').map(x=>x.trim()).filter(Boolean).slice(0,3);else if(k==='pass'){if(v.length<4){toast('ᴘᴀꜱꜱᴡᴏʀᴅ ᴛᴏᴏ ꜱʜᴏʀᴛ');return}p.pass=v}else p[k]=v;save();render();renderProfile();toast('ꜱᴀᴠᴇᴅ')};
function renderAdmin(){if(!isAdmin())return;q('#adminBody').innerHTML=`<div class="adminGrid"><button class="primary" data-add="match">＋ ᴜᴘᴄᴏᴍɪɴɢ ᴍᴀᴛᴄʜ</button><button class="primary" onclick="addScorecard()">＋ ꜱᴄᴏʀᴇᴄᴀʀᴅ / ʀᴇꜱᴜʟᴛ</button><button class="primary" data-add="news">＋ ɴᴇᴡꜱ</button><button class="primary" data-add="player">＋ ᴘʟᴀʏᴇʀ</button><button class="primary" data-add="honour">＋ ʜᴏɴᴏᴜʀ</button><button class="primary" data-add="gallery">＋ ᴀʟʙᴜᴍ ᴘʜᴏᴛᴏ</button><button class="primary" data-add="social">＋ ꜱᴏᴄɪᴀʟ</button><button class="primary" onclick="addAchievement()">＋ ᴀᴡᴀʀᴅ / ᴀᴄʜɪᴇᴠᴇᴍᴇɴᴛ</button><button class="primary" onclick="addLineup()">＋ ᴘᴜʙʟɪꜱʜ ᴘʟᴀʏɪɴɢ xɪ</button><button class="primary" onclick="go('stats')">✎ ᴘʟᴀʏᴇʀ ꜱᴛᴀᴛꜱ</button><button class="primary" onclick="go('lineup')">✎ ᴘʟᴀʏᴇʀ ᴀᴠᴀɪʟᴀʙɪʟɪᴛʏ</button><button class="primary" onclick="go('news')">📌 ᴘɪɴ / ᴜɴᴘɪɴ ɴᴇᴡꜱ</button><button class="primary" onclick="v6AddRecord()">＋ ᴛᴇᴀᴍ ʀᴇᴄᴏʀᴅ</button><button class="primary" onclick="v6AddTournament()">＋ ᴛᴏᴜʀɴᴀᴍᴇɴᴛ</button><button class="primary" onclick="v6AddOpponent()">＋ ᴏᴘᴘᴏɴᴇɴᴛ / ʜ2ʜ</button><button class="primary" onclick="go('matches')">✎ ꜰᴜʟʟ ꜱᴄᴏʀᴇᴄᴀʀᴅ / ᴘᴏꜱᴛᴇʀ</button></div><p class="adminHint">ᴀᴅᴍɪɴ ʜᴀꜱ ꜰᴜʟʟ ᴀᴅᴅ • ᴇᴅɪᴛ • ᴅᴇʟᴇᴛᴇ ᴄᴏɴᴛʀᴏʟ ꜰᴏʀ ᴛᴇᴀᴍ ᴅᴀᴛᴀ.</p>`;bindAdds()}
function bindAdds(){qa('[data-add]').forEach(b=>b.onclick=()=>{if(!isAdmin())return toast('ᴀᴅᴍɪɴ ᴏɴʟʏ');openEdit(b.dataset.add)})}window.editPlayer=id=>{if(isAdmin())openEdit('editPlayer',D.players.find(x=>x.id===id))};window.editSocial=i=>{if(isAdmin())openEdit('editSocial',D.socials[i])};function fileInput(){return '<label>ɪᴍᴀɢᴇ<input id="efile" type="file" accept="image/*"></label>'}
function openEdit(mode,obj=null){editMode=mode;editObj=obj;let h='',f='';if(mode==='match'){h='ᴀᴅᴅ ᴍᴀᴛᴄʜ';f='<label>ᴏᴘᴘᴏɴᴇɴᴛ<input id="e1"></label><label>ᴅᴀᴛᴇ / ᴛɪᴍᴇ<input id="e2"></label><label>ᴠᴇɴᴜᴇ<input id="e3"></label><label>ᴅᴇᴛᴀɪʟ / ʀᴇꜱᴜʟᴛ / ᴘᴏᴛᴍ<textarea id="e4"></textarea></label>'}if(mode==='news'){h='ᴀᴅᴅ ɴᴇᴡꜱ';f='<label>ᴛɪᴛʟᴇ<input id="e1"></label><label>ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ<textarea id="e2"></textarea></label>'}if(mode==='player'){h='ᴀᴅᴅ ᴘʟᴀʏᴇʀ';f='<label>ɴᴀᴍᴇ<input id="e1"></label><label>ʀᴏʟᴇ<input id="e2"></label><label>ᴘʟᴀʏɪɴɢ ᴅᴇᴛᴀɪʟ<textarea id="e3"></textarea></label>'+fileInput()}if(mode==='honour'){h='ᴀᴅᴅ ʜᴏɴᴏᴜʀ';f='<label>ʏᴇᴀʀ<input id="e1"></label><label>ʀᴇꜱᴜʟᴛ<input id="e2"></label><label>ᴛᴏᴜʀɴᴀᴍᴇɴᴛ<input id="e3"></label>'+fileInput()}if(mode==='gallery'){h='ᴀᴅᴅ ᴀʟʙᴜᴍ ᴘʜᴏᴛᴏ';f=fileInput()+'<label>ᴄᴀᴘᴛɪᴏɴ<input id="e1"></label><label>ᴀʟʙᴜᴍ<select id="e2"><option>TEAM PHOTOS</option><option selected>MEMORIES</option><option>UPDATES</option></select></label>'}if(mode==='social'){h='ᴀᴅᴅ ꜱᴏᴄɪᴀʟ';f='<label>ɴᴀᴍᴇ<input id="e1"></label><label>ʟɪɴᴋ<input id="e2" placeholder="https://..."></label><label>ɪᴄᴏɴ / ʟᴇᴛᴛᴇʀ<input id="e3" placeholder="▶"></label>'}if(mode==='editSocial'){h='ᴇᴅɪᴛ ꜱᴏᴄɪᴀʟ';f=`<label>ɴᴀᴍᴇ<input id="e1" value="${obj.name||''}"></label><label>ʟɪɴᴋ<input id="e2" value="${obj.url||''}" placeholder="https://..."></label><label>ɪᴄᴏɴ / ʟᴇᴛᴛᴇʀ<input id="e3" value="${obj.icon||''}"></label>${fileInput()}` }if(mode==='editPlayer'){h='ᴇᴅɪᴛ ᴘʟᴀʏᴇʀ';f=`<label>ɴᴀᴍᴇ<input id="e1" value="${obj.name}"></label><label>ʀᴏʟᴇ<input id="e2" value="${obj.role}"></label><label>ᴅᴇᴛᴀɪʟ<textarea id="e3">${obj.detail}</textarea></label>${fileInput()}`}q('#editTitle').textContent=h;q('#editFields').innerHTML=f;q('#editor').classList.add('show')}
const readImage=()=>new Promise(r=>{let f=q('#efile')?.files?.[0];if(!f)return r('');let x=new FileReader;x.onload=()=>r(x.result);x.readAsDataURL(f)});q('#editForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return;let img=await readImage(),v=id=>q('#'+id)?.value?.trim()||'';if(editMode==='match')D.matches.unshift({opponent:v('e1'),date:v('e2'),venue:v('e3'),note:v('e4')});if(editMode==='news')D.news.unshift({title:v('e1'),text:v('e2')});if(editMode==='player'){let id='RDM'+String(Math.max(0,...D.players.map(p=>+p.id.replace(/\D/g,'')))+1).padStart(3,'0');D.players.push({id,name:v('e1'),role:v('e2'),detail:v('e3'),pass:'Rdm#ChangeMe',image:img||'assets/logo.jpg',jersey:'',nick:'',bio:'',socials:[]})}if(editMode==='honour')D.honours.unshift({year:v('e1'),title:v('e2'),sub:v('e3'),image:img||'assets/logo.jpg'});if(editMode==='gallery'){if(!img)return toast('ꜱᴇʟᴇᴄᴛ ᴀɴ ɪᴍᴀɢᴇ');D.gallery.unshift({image:img,caption:v('e1'),album:v('e2')||'MEMORIES'})}if(editMode==='social')D.socials.push({name:v('e1'),url:v('e2'),icon:v('e3')||'↗'});if(editMode==='editSocial'){editObj.name=v('e1');editObj.url=v('e2');editObj.icon=v('e3')||editObj.icon||'↗';if(img)editObj.image=img}if(editMode==='editPlayer'){editObj.name=v('e1');editObj.role=v('e2');editObj.detail=v('e3');if(img)editObj.image=img}save();q('#editor').classList.remove('show');render();renderAdmin();toast('ꜱᴀᴠᴇᴅ')};
// Circular DP cropper
let crop={img:null,scale:1,x:0,y:0,drag:false,lx:0,ly:0};window.chooseDP=()=>{let inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=()=>{let f=inp.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{let im=new Image;im.onload=()=>{crop={img:im,scale:1,x:0,y:0,drag:false,lx:0,ly:0};q('#cropZoom').value=1;q('#cropModal').classList.add('show');drawCrop()};im.src=r.result};r.readAsDataURL(f)};inp.click()};
function drawCrop(){let c=q('#cropCanvas'),ctx=c.getContext('2d'),im=crop.img;if(!im)return;ctx.clearRect(0,0,320,320);let base=Math.max(320/im.width,320/im.height),sc=base*crop.scale,w=im.width*sc,h=im.height*sc,x=(320-w)/2+crop.x,y=(320-h)/2+crop.y;ctx.save();ctx.beginPath();ctx.arc(160,160,158,0,Math.PI*2);ctx.clip();ctx.drawImage(im,x,y,w,h);ctx.restore()}
q('#cropZoom').oninput=e=>{crop.scale=+e.target.value;drawCrop()};let cc=q('#cropCanvas');cc.onpointerdown=e=>{crop.drag=true;crop.lx=e.clientX;crop.ly=e.clientY;cc.setPointerCapture(e.pointerId)};cc.onpointermove=e=>{if(!crop.drag)return;crop.x+=e.clientX-crop.lx;crop.y+=e.clientY-crop.ly;crop.lx=e.clientX;crop.ly=e.clientY;drawCrop()};cc.onpointerup=()=>crop.drag=false;q('#cropSave').onclick=()=>{let p=currentPlayer();if(!p||!crop.img)return;let c=q('#cropCanvas'),out=document.createElement('canvas');out.width=512;out.height=512;let ctx=out.getContext('2d');ctx.drawImage(c,0,0,512,512);p.image=out.toDataURL('image/jpeg',.9);save();q('#cropModal').classList.remove('show');render();renderProfile();toast('ᴅᴘ ꜱᴀᴠᴇᴅ')};
bindAdds();render();if(session){let valid=session.mode==='admin'||D.players.some(p=>p.id===session.playerId);if(!valid){session=null;localStorage.removeItem(SK)}updateAuthUI()}

if(typeof saveLater!=='undefined'&&saveLater)save();
