/* RDM V5: scorecards, stats, achievements, home match cards, pinned news, albums, share profiles, availability, playing XI */
const XCOL={stats:'PlayerStats',achievements:'Achievements',availability:'Availability',lineups:'PlayingXI'};
let XD={stats:[],achievements:[],availability:[],lineups:[]}, galleryFilter='ALL';
function rdmWhen(ms){if(!ms)return '';const d=new Date(ms);return '🕒 '+d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})+' • '+d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',hour12:true});}
const xdoc=d=>({...d.data(),_docId:d.id});
async function xload(){try{const [s,a,v,l]=await Promise.all([rdmDB.collection(XCOL.stats).get(),rdmDB.collection(XCOL.achievements).get(),rdmDB.collection(XCOL.availability).get(),rdmDB.collection(XCOL.lineups).get()]);XD.stats=s.docs.map(xdoc);XD.achievements=a.docs.map(xdoc).sort((a,b)=>(b.createdMs||0)-(a.createdMs||0));XD.availability=v.docs.map(xdoc);XD.lineups=l.docs.map(xdoc).sort((a,b)=>(b.createdMs||0)-(a.createdMs||0));xrender()}catch(e){console.warn('V5 load',e)}}
const xv=id=>(document.getElementById(id)?.value||'').trim();
const xp=(label,def='')=>null;
const xnum=v=>Number(v||0)||0;
function xrender(){renderHomeExtras();renderStats();renderAchievements();renderAvailability();renderLineups();window.renderGalleryAlbums?.();renderPinnedNews();}
function renderHomeExtras(){let box=document.getElementById('homeMatchHub');if(!box){box=document.createElement('div');box.id='homeMatchHub';box.className='homeMatchHub';document.querySelector('#home .metrics').insertAdjacentElement('beforebegin',box)}
 const upcoming=D.matches.find(m=>!/won|lost|draw|result/i.test((m.note||'')+' '+(m.status||'')))||D.matches[0];const recent=D.matches.find(m=>/won|lost|draw|result/i.test((m.note||'')+' '+(m.status||'')));
 box.innerHTML=`<div class="miniMatch"><span>ɴᴇxᴛ ᴍᴀᴛᴄʜ</span>${upcoming?`<h3>${mini(upcoming.opponent)}</h3><p>${mini(upcoming.date||'')} • ${mini(upcoming.venue||'')}</p>`:'<p>ɴᴏ ᴜᴘᴄᴏᴍɪɴɢ ᴍᴀᴛᴄʜ</p>'}</div><div class="miniMatch"><span>ʀᴇᴄᴇɴᴛ ʀᴇꜱᴜʟᴛ</span>${recent?`<h3>${mini(recent.opponent)}</h3><p>${mini(recent.note||recent.status||'')}</p>`:'<p>ɴᴏ ʀᴇꜱᴜʟᴛ ᴀᴅᴅᴇᴅ ʏᴇᴛ</p>'}</div>`}
function renderStats(){const el=document.getElementById('statsList');if(!el)return;el.innerHTML=D.players.map(p=>{const s=XD.stats.find(z=>z.playerId===p.id)||{};return `<article class="statCard"><img src="${esc(p.image||'assets/logo.jpg')}"><h3>${mini(p.name)}</h3><div class="statNums"><b>${xnum(s.matches)}<small>ᴍᴀᴛᴄʜᴇꜱ</small></b><b>${xnum(s.runs)}<small>ʀᴜɴꜱ</small></b><b>${xnum(s.wickets)}<small>ᴡɪᴄᴋᴇᴛꜱ</small></b><b>${xnum(s.highScore)}<small>ʜɪɢʜ ꜱᴄᴏʀᴇ</small></b><b>${xnum(s.fours)}<small>4ꜱ</small></b><b>${xnum(s.sixes)}<small>6ꜱ</small></b><b>${xnum(s.fifties)}<small>50ꜱ</small></b><b>${xnum(s.hundreds)}<small>100ꜱ</small></b></div><p>ꜱᴛʀɪᴋᴇ ʀᴀᴛᴇ • ${xnum(s.strikeRate)} &nbsp; | &nbsp; ᴇᴄᴏɴᴏᴍʏ • ${xnum(s.economy)}</p><p>ʙᴇꜱᴛ ʙᴏᴡʟɪɴɢ • ${esc(s.bestBowling||'—')}</p>${rdmAdmin()?`<button class="tinyBtn" onclick="editStats('${p.id}')">✎ ᴇᴅɪᴛ ꜱᴛᴀᴛꜱ</button>`:''}</article>`}).join('')}
async function editStats(id){if(!rdmAdmin())return;const s=XD.stats.find(z=>z.playerId===id)||{};const ask=(n,v)=>xp(n,v??0);const matches=ask('Matches',s.matches);if(matches===null)return;const data={playerId:id,matches:xnum(matches),runs:xnum(ask('Runs',s.runs)),wickets:xnum(ask('Wickets',s.wickets)),highScore:xnum(ask('Highest Score',s.highScore)),bestBowling:ask('Best Bowling',s.bestBowling||'')||'',fours:xnum(ask('Fours',s.fours)),sixes:xnum(ask('Sixes',s.sixes)),fifties:xnum(ask('50s',s.fifties)),hundreds:xnum(ask('100s',s.hundreds)),runOuts:xnum(ask('Run Outs',s.runOuts)),strikeRate:xnum(ask('Strike Rate',s.strikeRate)),economy:xnum(ask('Economy',s.economy)),updatedAt:rdmStamp()};await rdmDB.collection(XCOL.stats).doc(id).set(data,{merge:true});await xload()}
function renderAchievements(){const el=document.getElementById('achievementList');if(!el)return;el.innerHTML=XD.achievements.length?XD.achievements.map(a=>`<article class="card"><h3>🏆 ${mini(a.title)}</h3><p>${mini(a.playerName||'TEAM')} • ${mini(a.detail||'')}</p>${rdmAdmin()?`<button class="tinyBtn" onclick="xdelete('${XCOL.achievements}','${a._docId}')">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴀᴄʜɪᴇᴠᴇᴍᴇɴᴛ ᴀᴅᴅᴇᴅ ʏᴇᴛ</div>'}
async function addAchievement(){const title=xp('Achievement / Award');if(!title)return;const playerName=xp('Player Name (or TEAM)','TEAM');const detail=xp('Details','');await rdmDB.collection(XCOL.achievements).add({title,playerName,detail,createdMs:Date.now(),updatedAt:rdmStamp()});await xload()}
function renderAvailability(){const el=document.getElementById('availabilityList');if(!el)return;el.innerHTML=D.players.map(p=>{const a=XD.availability.find(z=>z.playerId===p.id);const st=a?.status||'NOT SET';return `<div class="availabilityRow"><span>${mini(p.name)}</span><b class="${st==='AVAILABLE'?'available':st==='UNAVAILABLE'?'unavailable':''}">${mini(st)}</b>${(rdmAdmin()||(session?.mode==='player'&&session.playerId===p.id))?`<button class="tinyBtn" onclick="setAvailability('${p.id}')">ᴄʜᴀɴɢᴇ</button>`:''}</div>`}).join('')}
async function setAvailability(id){if(!rdmAdmin()&&!(session?.mode==='player'&&session.playerId===id))return;const status=(xp('Type AVAILABLE or UNAVAILABLE','AVAILABLE')||'').toUpperCase();if(!['AVAILABLE','UNAVAILABLE'].includes(status))return toast('ᴜꜱᴇ ᴀᴠᴀɪʟᴀʙʟᴇ / ᴜɴᴀᴠᴀɪʟᴀʙʟᴇ');await rdmDB.collection(XCOL.availability).doc(id).set({playerId:id,status,updatedAt:rdmStamp()},{merge:true});await xload()}
function renderLineups(){const el=document.getElementById('lineupList');if(!el)return;el.innerHTML=XD.lineups.length?XD.lineups.map(l=>`<article class="card lineupCard"><h3>${mini(l.title||'PLAYING XI')}</h3><p>${mini(l.match||'')}</p><div class="xiGrid">${(l.players||[]).map((id,i)=>{const p=D.players.find(x=>x.id===id);return `<span>${i+1}. ${mini(p?.name||id)}</span>`}).join('')}</div>${(l.subs||[]).length?`<p>ꜱᴜʙꜱ • ${(l.subs||[]).map(id=>mini(D.players.find(x=>x.id===id)?.name||id)).join(' • ')}</p>`:''}${rdmAdmin()?`<button class="tinyBtn" onclick="xdelete('${XCOL.lineups}','${l._docId}')">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴘʟᴀʏɪɴɢ xɪ ᴘᴜʙʟɪꜱʜᴇᴅ ʏᴇᴛ</div>'}
async function addLineup(){const title=xp('Title','PLAYING XI');if(!title)return;const match=xp('Match / Opponent','');const ids=xp('Enter 11 Player IDs separated by comma','RDM001,RDM002,RDM003,RDM004,RDM005,RDM006,RDM007,RDM008,RDM009,RDM010,RDM011');if(!ids)return;const players=ids.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,11);const subs=(xp('Substitute Player IDs separated by comma','RDM012,RDM013,RDM014,RDM015')||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);await rdmDB.collection(XCOL.lineups).add({title,match,players,subs,createdMs:Date.now(),updatedAt:rdmStamp()});await xload()}
function legacyGalleryAlbums(){const g=document.getElementById('galleryList');if(!g)return;let bar=document.getElementById('albumFilters');if(!bar){bar=document.createElement('div');bar.id='albumFilters';bar.className='albumFilters';g.before(bar)}const cats=['ALL','TEAM PHOTOS','MEMORIES','UPDATES'];bar.innerHTML=cats.map(c=>`<button class="tinyBtn ${galleryFilter===c?'on':''}" onclick="galleryFilter='${c}';renderGalleryAlbums()">${mini(c)}</button>`).join('');const arr=galleryFilter==='ALL'?D.gallery:D.gallery.filter(x=>(x.album||'MEMORIES').toUpperCase()===galleryFilter);g.innerHTML=arr.length?arr.map((x)=>`<figure><img src="${x.image}" onclick="zoom(this.src)"><figcaption><b>${mini(x.album||'MEMORIES')}</b><br>${mini(x.caption||'RDM MEMORY')}<span class="contentTime">${rdmWhen(x.createdMs)}</span></figcaption>${rdmAdmin()?`<button class="tinyBtn" onclick="xdelete('Gallery','${x._docId}')">ᴅᴇʟᴇᴛᴇ</button>`:''}</figure>`).join(''):'<div class="empty">ɴᴏ ᴘʜᴏᴛᴏꜱ ɪɴ ᴛʜɪꜱ ᴀʟʙᴜᴍ</div>'}
function renderPinnedNews(){const n=document.getElementById('newsList');if(!n)return;const sorted=[...D.news].sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||(b.createdMs||0)-(a.createdMs||0));n.innerHTML=sorted.length?sorted.map(x=>`<article class="card ${x.pinned?'pinnedNews':''}">${x.pinned?'<span class="pinTag">📌 ᴘɪɴɴᴇᴅ</span>':''}<div class="contentTime topTime">${rdmWhen(x.createdMs)}</div><h3>${mini(x.title)}</h3><p class="preserveLines">${mini(x.text)}</p>${rdmAdmin()?`<div class="contentActions"><button type="button" class="tinyBtn" onclick="editNews('${x._docId}')">✎ ᴇᴅɪᴛ</button><button type="button" class="tinyBtn" onclick="togglePin('${x._docId}',${!x.pinned})">${x.pinned?'ᴜɴᴘɪɴ':'📌 ᴘɪɴ'}</button><button type="button" class="tinyBtn deleteBtn" onclick="xdelete('News','${x._docId}')">🗑 ᴅᴇʟᴇᴛᴇ</button></div>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ ʏᴇᴛ</div>'}
async function editNews(id){if(!rdmAdmin())return;const x=(D.news||[]).find(n=>n._docId===id)||{};if(typeof window.rdmUnifiedModal!=='function')return toast('ꜰᴏʀᴍ ʟᴏᴀᴅɪɴɢ');window.rdmUnifiedModal('EDIT NEWS',[{name:'title',label:'TITLE',value:x.title||'',required:true},{name:'text',label:'NEWS / ANNOUNCEMENT',type:'textarea',value:x.text||'',rows:6,required:true}],async d=>{await rdmDB.collection('News').doc(id).set({title:String(d.title||'').trim(),text:String(d.text||'').trim(),updatedAt:rdmStamp()},{merge:true});await rdmLoadAll();setTimeout(xrender,80);toast('ɴᴇᴡꜱ ᴜᴘᴅᴀᴛᴇᴅ')})}
async function togglePin(id,pinned){if(!rdmAdmin())return;try{await rdmDB.collection('News').doc(id).set({pinned,updatedAt:rdmStamp()},{merge:true});await rdmLoadAll();setTimeout(xrender,100);toast(pinned?'ɴᴇᴡꜱ ᴘɪɴɴᴇᴅ':'ɴᴇᴡꜱ ᴜɴᴘɪɴɴᴇᴅ')}catch(e){console.error(e);toast('ᴘɪɴ ᴀᴄᴛɪᴏɴ ꜰᴀɪʟᴇᴅ')}}
async function xdelete(col,id){if(!rdmAdmin())return;const run=async()=>{await rdmDB.collection(col).doc(id).delete();if(col==='Gallery'||col==='News')await rdmLoadAll();else await xload();toast('ᴅᴇʟᴇᴛᴇᴅ')};if(typeof window.rdmConfirmModal==='function')return window.rdmConfirmModal('DELETE ITEM','THIS ACTION CANNOT BE UNDONE.',run);return run()}
window.editNews=editNews;window.togglePin=togglePin;window.xdelete=xdelete;
window.sharePlayerProfile=async id=>{const p=D.players.find(x=>x.id===id);const url=location.origin+location.pathname+'#player='+encodeURIComponent(id);const data={title:p?.name||'RDM Player',text:`${p?.name||id} • Rehan Dominators Mahuawan`,url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(url);toast('ᴘʀᴏꜰɪʟᴇ ʟɪɴᴋ ᴄᴏᴘɪᴇᴅ')}}catch(e){}}
const oldOpen=window.openPlayerProfile;window.openPlayerProfile=function(id){oldOpen(id);setTimeout(()=>{const c=document.querySelector('#publicProfileModal .publicProfileCard');if(c&&!c.querySelector('.shareProfileBtn'))c.insertAdjacentHTML('beforeend',`<button type="button" class="shareProfileBtn" onclick="sharePlayerProfile('${id}')">↗ ꜱʜᴀʀᴇ ᴘʀᴏꜰɪʟᴇ</button>`)},50)};
// Add scorecard controls to existing match cards and admin helper
window.addScorecard=async function(){if(!rdmAdmin())return;const opponent=xp('Opponent');if(!opponent)return;const date=xp('Date','');const venue=xp('Venue','');const ourScore=xp('RDM Score (example 145/6)','');const oppScore=xp('Opponent Score','');const result=xp('Result','');const potm=xp('Player of the Match','');await rdmDB.collection('Matches').add({opponent,date,venue,note:result,status:'RESULT',ourScore,oppScore,potm,createdMs:Date.now(),updatedAt:rdmStamp()});await rdmLoadAll()}
function enhanceMatchCards(){const el=document.getElementById('matchList');if(!el)return;el.innerHTML=D.matches.length?D.matches.map(m=>`<article class="card scoreCard"><h3>RDM 🆚 ${mini(m.opponent)}</h3><p>${mini(m.date||'')} • ${mini(m.venue||'')}</p>${m.ourScore||m.oppScore?`<div class="scoreLine"><b>RDM ${esc(m.ourScore||'—')}</b><b>${mini(m.opponent)} ${esc(m.oppScore||'—')}</b></div>`:''}<p class="preserveLines">${mini(m.note||'')}</p>${m.potm?`<p>🏅 ᴘʟᴀʏᴇʀ ᴏꜰ ᴛʜᴇ ᴍᴀᴛᴄʜ • ${mini(m.potm)}</p>`:''}${rdmAdmin()?`<button class="tinyBtn" onclick="xdelete('Matches','${m._docId}')">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴍᴀᴛᴄʜ ᴀᴅᴅᴇᴅ ʏᴇᴛ</div>'}
const baseRender=window.render;window.render=function(){baseRender();enhanceMatchCards();setTimeout(xrender,0)};
document.addEventListener('click',e=>{if(e.target?.id==='addScorecard')addScorecard();if(e.target?.id==='addAchievement')addAchievement();if(e.target?.id==='addLineup')addLineup()});
setTimeout(()=>{xload();const hash=location.hash.match(/player=([^&]+)/);if(hash)setTimeout(()=>openPlayerProfile(decodeURIComponent(hash[1])),500)},700);
