/* RDM V4 cloud backend: Firestore persistence + public profiles + admin/player profile controls */
const RCOL={players:'TeamPlayers',matches:'Matches',news:'News',honours:'Honours',gallery:'Gallery',socials:'Socials'};
const DEFAULT_SOCIAL_URLS={INSTAGRAM:'https://www.instagram.com/rehandominatorsmahuawann/',YOUTUBE:'https://www.youtube.com/@rehan_dominators_mahuawan',TELEGRAM:'https://t.me/rehandominatorsmahuawan',WHATSAPP:'https://whatsapp.com/channel/0029Vb8icRM3WHTQGQtM4G3j'};
let rdmRemoteReady=false,rdmLoading=false,rdmCropTarget=null;
const rdmStamp=()=>firebase.firestore.FieldValue.serverTimestamp();
const rdmDocData=d=>({...d.data(),_docId:d.id});
const rdmAdmin=()=>session?.mode==='admin';
const rdmPlayer=()=>session?.mode==='player'?D.players.find(p=>p.id===session.playerId):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>/^https?:\/\//i.test(String(u||''))?String(u):'';
function rdmRefresh(){render();if(session?.mode==='player')renderProfile();if(session?.mode==='admin')renderAdmin();}
async function rdmCompressFile(file,max=1000,quality=.72){
  if(!file)return'';const url=await new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});
  const im=await new Promise((res,rej)=>{const x=new Image;x.onload=()=>res(x);x.onerror=rej;x.src=url});const scale=Math.min(1,max/Math.max(im.width,im.height));
  const c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);
  let out=c.toDataURL('image/jpeg',quality);if(out.length>720000)out=c.toDataURL('image/jpeg',.55);if(out.length>900000)throw new Error('IMAGE_TOO_LARGE');return out;
}
async function rdmSeedIfNeeded(){if(!rdmAdmin())return;
  if((await rdmDB.collection(RCOL.players).limit(1).get()).empty){const b=rdmDB.batch();D.players.forEach((p,i)=>b.set(rdmDB.collection(RCOL.players).doc(p.id),{id:p.id,name:p.name,role:p.role,detail:p.detail,image:p.image||'assets/logo.jpg',jersey:p.jersey||'',order:i+1,active:true,updatedAt:rdmStamp()}));await b.commit();}
  if((await rdmDB.collection(RCOL.honours).limit(1).get()).empty){const b=rdmDB.batch();D.honours.forEach((h,i)=>b.set(rdmDB.collection(RCOL.honours).doc('h'+String(i+1).padStart(2,'0')),{...h,order:i+1,updatedAt:rdmStamp()}));await b.commit();}
  if((await rdmDB.collection(RCOL.socials).limit(1).get()).empty){const defs=[{id:'instagram',name:'INSTAGRAM',url:DEFAULT_SOCIAL_URLS.INSTAGRAM,icon:'IG',displayName:'RDM INSTAGRAM',order:1},{id:'facebook',name:'FACEBOOK',url:'',icon:'f',displayName:'RDM FACEBOOK',order:2},{id:'youtube',name:'YOUTUBE',url:DEFAULT_SOCIAL_URLS.YOUTUBE,icon:'▶',displayName:'RDM YOUTUBE',order:3},{id:'telegram',name:'TELEGRAM',url:DEFAULT_SOCIAL_URLS.TELEGRAM,icon:'✈',displayName:'RDM TELEGRAM',order:4},{id:'whatsapp',name:'WHATSAPP',url:DEFAULT_SOCIAL_URLS.WHATSAPP,icon:'◉',displayName:'RDM WHATSAPP',order:5}];const b=rdmDB.batch();defs.forEach(x=>{const{id,...z}=x;b.set(rdmDB.collection(RCOL.socials).doc(id),{...z,image:'',updatedAt:rdmStamp()})});await b.commit();}
  await rdmDB.collection(RCOL.socials).doc('instagram').set({name:'INSTAGRAM',displayName:'RDM INSTAGRAM',url:DEFAULT_SOCIAL_URLS.INSTAGRAM,icon:'IG',order:1,updatedAt:rdmStamp()},{merge:true});
}
async function rdmLoadAll(){if(rdmLoading)return;rdmLoading=true;try{const[ps,ms,ns,hs,gs,ss,profiles]=await Promise.all([rdmDB.collection(RCOL.players).get(),rdmDB.collection(RCOL.matches).get(),rdmDB.collection(RCOL.news).get(),rdmDB.collection(RCOL.honours).get(),rdmDB.collection(RCOL.gallery).get(),rdmDB.collection(RCOL.socials).get(),rdmDB.collection('PlayerProfiles').get()]);
  if(!ps.empty)D.players=ps.docs.map(rdmDocData).sort((a,b)=>(a.order||999)-(b.order||999)).map(p=>({id:p.id,name:p.name,role:p.role,detail:p.detail,image:p.image||'assets/logo.jpg',jersey:p.jersey||'',nick:'',bio:'',socials:[],_docId:p._docId}));
  D.matches=ms.docs.map(rdmDocData).sort((a,b)=>(b.createdMs||0)-(a.createdMs||0));D.news=ns.docs.map(rdmDocData).sort((a,b)=>(b.createdMs||0)-(a.createdMs||0));if(!hs.empty)D.honours=hs.docs.map(rdmDocData).sort((a,b)=>(a.order||999)-(b.order||999));D.gallery=gs.docs.map(rdmDocData).sort((a,b)=>(b.createdMs||0)-(a.createdMs||0));if(!ss.empty)D.socials=ss.docs.map(rdmDocData).sort((a,b)=>(a.order||999)-(b.order||999));
  profiles.docs.forEach(d=>{const pr=d.data(),p=D.players.find(x=>x.id===pr.playerId);if(p){['jersey','nick','bio','image'].forEach(k=>{if(pr[k]!==undefined&&pr[k]!==null&&pr[k]!=='')p[k]=pr[k]});if(Array.isArray(pr.socials))p.socials=pr.socials;p._profileUid=d.id;}});rdmRemoteReady=true;rdmRefresh();
}catch(e){console.error(e);toast('ᴅᴀᴛᴀ ꜱʏɴᴄ ᴇʀʀᴏʀ')}finally{rdmLoading=false}}
window.rdmBackendAuthReady=async(user,account)=>{if(account?.role==='admin')await rdmSeedIfNeeded();await rdmLoadAll()};rdmLoadAll();document.addEventListener('visibilitychange',()=>{if(!document.hidden)rdmLoadAll()});

async function rdmProfileUid(playerId){const p=D.players.find(x=>x.id===playerId);if(p?._profileUid)return p._profileUid;if(session?.mode==='player'&&session.playerId===playerId)return rdmAuth.currentUser?.uid||null;if(rdmAdmin()){const s=await rdmDB.collection('Accounts').where('playerId','==',playerId).limit(1).get();return s.empty?null:s.docs[0].id}return null}
async function rdmProfileWrite(p,extra={}){const uid=await rdmProfileUid(p.id);if(!uid)throw new Error('PROFILE_ACCOUNT_NOT_FOUND');if(!rdmAdmin()&&(!rdmAuth.currentUser||session?.playerId!==p.id))throw new Error('NOT_ALLOWED');const data={playerId:p.id,jersey:p.jersey||'',nick:p.nick||'',bio:p.bio||'',socials:Array.isArray(p.socials)?p.socials.slice(0,3):[],image:p.image||'',updatedAt:rdmStamp(),...extra};await rdmDB.collection('PlayerProfiles').doc(uid).set(data,{merge:true});p._profileUid=uid}

function socialObj(x,i){return typeof x==='string'?{name:'SOCIAL '+(i+1),url:x}:x||{}}
function profileHtml(p,editable=false,adminEdit=false){const socials=(p.socials||[]).map(socialObj).filter(s=>s.url||s.name);const sh=socials.length?`<div class="profileSocialList">${socials.map((s,i)=>`<div class="profileSocialRow"><a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener">${mini(s.name||('SOCIAL '+(i+1)))} ↗</a>${editable?`<button class="tinyBtn" onclick="editOwnSocial(${i})">✎</button><button class="tinyBtn danger" onclick="deleteOwnSocial(${i})">×</button>`:''}</div>`).join('')}</div>`:'<p class="mutedMini">ɴᴏ ꜱᴏᴄɪᴀʟ ʟɪɴᴋꜱ</p>';
  return `<article class="profileCard publicProfileCard"><img class="profileAvatar" src="${esc(p.image||'assets/logo.jpg')}"><h2>${mini(p.name)}</h2><div class="profileIdentity"><div class="identityItem"><span>ᴘʟᴀʏᴇʀ ɪᴅ</span><strong>${miniId(p.id)}</strong></div><div class="identityDivider"></div><div class="identityItem"><span>ᴊᴇʀꜱᴇʏ ɴᴜᴍʙᴇʀ</span><strong>${p.jersey?'#'+esc(p.jersey):'—'}</strong></div></div>${p.nick?`<p class="profileNick">${mini(p.nick)}</p>`:''}<div class="profileOfficial"><b>${mini(p.role)}</b><br>${mini(p.detail)}</div>${p.bio?`<div class="profileBio">${mini(p.bio)}</div>`:''}${sh}${editable?`<div class="profileActions"><button class="secondary" onclick="chooseDP()">✎ ᴘʜᴏᴛᴏ</button><button class="secondary" onclick="selfEdit('jersey')">✎ ᴊᴇʀꜱᴇʏ</button><button class="secondary" onclick="selfEdit('nick')">✎ ɴɪᴄᴋɴᴀᴍᴇ</button><button class="secondary" onclick="selfEdit('bio')">✎ ʙɪᴏ</button><button class="secondary" onclick="addOwnSocial()">＋ ꜱᴏᴄɪᴀʟ</button><button class="secondary" onclick="selfEdit('pass')">🔐 ᴘᴀꜱꜱᴡᴏʀᴅ</button></div>`:''}${adminEdit?`<div class="profileActions"><button class="secondary" onclick="adminChooseDP('${p.id}')">✎ ᴅᴘ</button><button class="secondary" onclick="editPlayer('${p.id}')">✎ ᴘʀᴏꜰɪʟᴇ</button></div>`:''}</article>`}

render=function(){q('#players').innerHTML=D.players.map(p=>`<article class="player clickablePlayer" onclick="openPlayerProfile('${p.id}')"><div class="photo"><img src="${esc(p.image||'assets/logo.jpg')}" alt="${esc(p.name)}"></div><div class="pbody"><span class="badge">${miniId(p.id)}${p.jersey?' • #'+esc(p.jersey):''}</span><h3>${mini(p.name)}</h3><b>${mini(p.role)}</b><p>${mini(p.detail)}</p>${p.nick?`<p>ɴɪᴄᴋɴᴀᴍᴇ • ${mini(p.nick)}</p>`:''}<button class="tinyBtn viewProfileBtn" onclick="event.stopPropagation();openPlayerProfile('${p.id}')">ᴠɪᴇᴡ ᴘʀᴏꜰɪʟᴇ</button>${rdmAdmin()?`<button class="tinyBtn" onclick="event.stopPropagation();editPlayer('${p.id}')">✎ ᴇᴅɪᴛ</button>`:''}</div></article>`).join('');
 q('#honourList').innerHTML=D.honours.map((h,i)=>`<article class="honour"><div class="trophy"><img src="${h.image}" onclick="zoom('${h.image}')"></div><h3>${h.year} • ${mini(h.title)}</h3><p>${mini(h.sub)}</p>${rdmAdmin()?`<button class="tinyBtn" onclick="removeItem('honours',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join('');
 q('#matchList').innerHTML=D.matches.length?D.matches.map((m,i)=>`<article class="card"><h3>${mini(m.opponent)}</h3><p>${mini(m.date)} • ${mini(m.venue)}</p><p>${mini(m.note)}</p>${rdmAdmin()?`<button class="tinyBtn" onclick="removeItem('matches',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴍᴀᴛᴄʜ ᴀᴅᴅᴇᴅ ʏᴇᴛ</div>';
 q('#newsList').innerHTML=D.news.length?D.news.map((n,i)=>`<article class="card"><h3>${mini(n.title)}</h3><p class="newsText">${mini(n.text)}</p>${rdmAdmin()?`<button class="tinyBtn" onclick="removeItem('news',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</article>`).join(''):'<div class="empty">ɴᴏ ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ ʏᴇᴛ</div>';
 q('#galleryList').innerHTML=D.gallery.length?D.gallery.map((g,i)=>`<figure><img src="${g.image}" onclick="zoom(this.src)"><figcaption>${mini(g.caption||'RDM MEMORY')}</figcaption>${rdmAdmin()?`<button class="tinyBtn" onclick="removeItem('gallery',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</figure>`).join(''):'<div class="empty">ɴᴏ ɢᴀʟʟᴇʀʏ ᴘʜᴏᴛᴏ ᴀᴅᴅᴇᴅ ʏᴇᴛ</div>';
 q('#socialList').innerHTML=D.socials.map((o,i)=>{o=Array.isArray(o)?{name:o[0],url:o[1],icon:'↗'}:o;const media=o.image?`<img src="${o.image}" alt="${esc(o.name)}">`:`<span>${esc(o.icon||'↗')}</span>`;const open=o.url?`<a class="primary socialAction" href="${esc(safeUrl(o.url))}" target="_blank" rel="noopener">ᴏᴘᴇɴ</a>`:`<button class="secondary socialAction" disabled>ʟɪɴᴋ ɴᴏᴛ ᴀᴅᴅᴇᴅ</button>`;return `<article class="socialCard"><div class="socialIcon">${media}</div><h3>${mini(o.displayName||o.name)}</h3><p class="socialPlatform">${mini(o.name)}</p><div class="socialActions">${open}${rdmAdmin()?`<button class="tinyBtn socialAction" onclick="editSocial(${i})">✎ ᴇᴅɪᴛ</button><button class="tinyBtn socialAction danger" onclick="removeItem('socials',${i})">ᴅᴇʟᴇᴛᴇ</button>`:''}</div></article>`}).join('');updateAuthUI()};
renderProfile=function(){const p=rdmPlayer();if(p)q('#profileBody').innerHTML=profileHtml(p,true,false)};
window.openPlayerProfile=id=>{const p=D.players.find(x=>x.id===id);if(!p)return;let m=q('#publicProfileModal');if(!m){m=document.createElement('div');m.id='publicProfileModal';m.className='modal';m.innerHTML='<div class="dialog publicDialog"><button class="close" type="button">×</button><div id="publicProfileBody"></div></div>';document.body.appendChild(m);m.querySelector('.close').onclick=()=>m.classList.remove('show')}q('#publicProfileBody').innerHTML=profileHtml(p,false,rdmAdmin());m.classList.add('show')};

window.selfEdit=async k=>{const p=rdmPlayer();if(!p)return;if(k==='pass'){const old=prompt('CURRENT PASSWORD');if(!old)return;const nw=prompt('NEW PASSWORD • MINIMUM 6 CHARACTERS');if(!nw)return;if(nw.length<6)return toast('ᴍɪɴɪᴍᴜᴍ 6 ᴄʜᴀʀᴀᴄᴛᴇʀꜱ');try{const u=rdmAuth.currentUser,cred=firebase.auth.EmailAuthProvider.credential(u.email,old);await u.reauthenticateWithCredential(cred);await u.updatePassword(nw);toast('ᴘᴀꜱꜱᴡᴏʀᴅ ᴄʜᴀɴɢᴇᴅ')}catch(e){console.error(e);toast('ᴄᴜʀʀᴇɴᴛ ᴘᴀꜱꜱᴡᴏʀᴅ ᴡʀᴏɴɢ')}return}const label={jersey:'JERSEY NUMBER',nick:'NICKNAME',bio:'BIO'}[k],v=prompt(label,p[k]||'');if(v===null)return;p[k]=v.trim();try{await rdmProfileWrite(p);rdmRefresh();toast('ꜱᴀᴠᴇᴅ ᴏɴʟɪɴᴇ')}catch(e){console.error(e);toast('ꜱᴀᴠᴇ ꜰᴀɪʟᴇᴅ')}};
window.addOwnSocial=async()=>{const p=rdmPlayer();if(!p)return;if((p.socials||[]).length>=3)return toast('ᴍᴀx 3 ꜱᴏᴄɪᴀʟꜱ');const name=prompt('SOCIAL NAME • EXAMPLE: INSTAGRAM');if(!name)return;const url=prompt('SOCIAL LINK • https://...');if(!safeUrl(url))return toast('ᴠᴀʟɪᴅ ʟɪɴᴋ ʀᴇǫᴜɪʀᴇᴅ');p.socials=[...(p.socials||[]),{name:name.trim(),url:url.trim()}].slice(0,3);await rdmProfileWrite(p);rdmRefresh();toast('ꜱᴏᴄɪᴀʟ ᴀᴅᴅᴇᴅ')};
window.editOwnSocial=async i=>{const p=rdmPlayer(),s=socialObj(p?.socials?.[i],i);if(!p||!s)return;const name=prompt('SOCIAL NAME',s.name||'');if(name===null)return;const url=prompt('SOCIAL LINK',s.url||'');if(url===null||!safeUrl(url))return toast('ᴠᴀʟɪᴅ ʟɪɴᴋ ʀᴇǫᴜɪʀᴇᴅ');p.socials[i]={name:name.trim()||('SOCIAL '+(i+1)),url:url.trim()};await rdmProfileWrite(p);rdmRefresh();toast('ꜱᴏᴄɪᴀʟ ᴜᴘᴅᴀᴛᴇᴅ')};
window.deleteOwnSocial=async i=>{const p=rdmPlayer();if(!p)return;p.socials.splice(i,1);await rdmProfileWrite(p);rdmRefresh();toast('ꜱᴏᴄɪᴀʟ ᴅᴇʟᴇᴛᴇᴅ')};

const originalChooseDP=window.chooseDP;window.chooseDP=()=>{rdmCropTarget=rdmPlayer()?.id||null;originalChooseDP()};window.adminChooseDP=id=>{if(!rdmAdmin())return;rdmCropTarget=id;originalChooseDP()};
q('#cropSave').onclick=async()=>{const p=D.players.find(x=>x.id===(rdmCropTarget||rdmPlayer()?.id));if(!p||!crop.img)return;const src=q('#cropCanvas'),out=document.createElement('canvas');out.width=320;out.height=320;out.getContext('2d').drawImage(src,0,0,320,320);p.image=out.toDataURL('image/jpeg',.72);try{if(rdmAdmin())await rdmDB.collection(RCOL.players).doc(p.id).set({image:p.image,updatedAt:rdmStamp()},{merge:true});await rdmProfileWrite(p);q('#cropModal').classList.remove('show');rdmCropTarget=null;await rdmLoadAll();toast('ᴅᴘ ꜱᴀᴠᴇᴅ ᴏɴʟɪɴᴇ')}catch(e){console.error(e);toast('ᴅᴘ ꜱᴀᴠᴇ ꜰᴀɪʟᴇᴅ')}};

window.removeItem=async(k,i)=>{if(!rdmAdmin())return toast('ᴀᴅᴍɪɴ ᴏɴʟʏ');const item=D[k]?.[i],col=RCOL[k];if(!item||!col)return;try{if(item._docId)await rdmDB.collection(col).doc(item._docId).delete();D[k].splice(i,1);rdmRefresh();toast('ᴅᴇʟᴇᴛᴇᴅ ᴏɴʟɪɴᴇ')}catch(e){console.error(e);toast('ᴅᴇʟᴇᴛᴇ ꜰᴀɪʟᴇᴅ')}};
window.editPlayer=id=>{if(rdmAdmin())openEdit('editPlayer',D.players.find(x=>x.id===id))};window.editSocial=i=>{if(rdmAdmin())openEdit('editSocial',D.socials[i])};
openEdit=function(mode,obj=null){editMode=mode;editObj=obj;let h='',f='';const fi='<label>ɪᴍᴀɢᴇ<input id="efile" type="file" accept="image/*"></label>';
 if(mode==='match'){h='ᴀᴅᴅ ᴍᴀᴛᴄʜ';f='<label>ᴏᴘᴘᴏɴᴇɴᴛ<input id="e1"></label><label>ᴅᴀᴛᴇ / ᴛɪᴍᴇ<input id="e2"></label><label>ᴠᴇɴᴜᴇ<input id="e3"></label><label>ᴅᴇᴛᴀɪʟ / ʀᴇꜱᴜʟᴛ / ᴘᴏᴛᴍ<textarea id="e4"></textarea></label>'}
 if(mode==='news'){h='ᴀᴅᴅ ɴᴇᴡꜱ';f='<label>ᴛɪᴛʟᴇ<input id="e1"></label><label>ᴀɴɴᴏᴜɴᴄᴇᴍᴇɴᴛ<textarea id="e2"></textarea></label>'}
 if(mode==='player'){h='ᴀᴅᴅ ᴘʟᴀʏᴇʀ';f='<label>ɴᴀᴍᴇ<input id="e1"></label><label>ʀᴏʟᴇ<input id="e2"></label><label>ᴘʟᴀʏɪɴɢ ᴅᴇᴛᴀɪʟ<textarea id="e3"></textarea></label>'+fi}
 if(mode==='honour'){h='ᴀᴅᴅ ʜᴏɴᴏᴜʀ';f='<label>ʏᴇᴀʀ<input id="e1"></label><label>ʀᴇꜱᴜʟᴛ<input id="e2"></label><label>ᴛᴏᴜʀɴᴀᴍᴇɴᴛ<input id="e3"></label>'+fi}
 if(mode==='gallery'){h='ᴀᴅᴅ ᴘʜᴏᴛᴏ';f=fi+'<label>ᴄᴀᴘᴛɪᴏɴ<input id="e1"></label>'}
 if(mode==='social'){h='ᴀᴅᴅ ꜱᴏᴄɪᴀʟ';f='<label>ᴘʟᴀᴛꜰᴏʀᴍ<input id="e1" placeholder="INSTAGRAM"></label><label>ᴅɪꜱᴘʟᴀʏ ɴᴀᴍᴇ<input id="e4" placeholder="RDM INSTAGRAM"></label><label>ʟɪɴᴋ<input id="e2" placeholder="https://..."></label><label>ɪᴄᴏɴ<input id="e3" placeholder="IG"></label>'+fi}
 if(mode==='editSocial'){h='ᴇᴅɪᴛ ꜱᴏᴄɪᴀʟ';f=`<label>ᴘʟᴀᴛꜰᴏʀᴍ<input id="e1" value="${esc(obj.name||'')}"></label><label>ᴅɪꜱᴘʟᴀʏ ɴᴀᴍᴇ<input id="e4" value="${esc(obj.displayName||obj.name||'')}"></label><label>ʟɪɴᴋ<input id="e2" value="${esc(obj.url||'')}"></label><label>ɪᴄᴏɴ<input id="e3" value="${esc(obj.icon||'')}"></label>${fi}`}
 if(mode==='editPlayer'){h='ᴇᴅɪᴛ ᴘʟᴀʏᴇʀ';f=`<label>ɴᴀᴍᴇ<input id="e1" value="${esc(obj.name)}"></label><label>ʀᴏʟᴇ<input id="e2" value="${esc(obj.role)}"></label><label>ᴘʟᴀʏɪɴɢ ᴅᴇᴛᴀɪʟ<textarea id="e3">${esc(obj.detail)}</textarea></label><label>ᴊᴇʀꜱᴇʏ<input id="e4" value="${esc(obj.jersey||'')}"></label><label>ɴɪᴄᴋɴᴀᴍᴇ<input id="e5" value="${esc(obj.nick||'')}"></label><label>ʙɪᴏ<textarea id="e6">${esc(obj.bio||'')}</textarea></label>${fi}`}
 q('#editTitle').textContent=h;q('#editFields').innerHTML=f;q('#editor').classList.add('show')};
q('#editForm').onsubmit=async e=>{e.preventDefault();if(!rdmAdmin())return toast('ᴀᴅᴍɪɴ ᴏɴʟʏ');const v=id=>q('#'+id)?.value?.trim()||'',file=q('#efile')?.files?.[0];try{let img='';if(file)img=await rdmCompressFile(file);const now=Date.now();
 if(editMode==='match')await rdmDB.collection(RCOL.matches).add({opponent:v('e1'),date:v('e2'),venue:v('e3'),note:v('e4'),createdMs:now,updatedAt:rdmStamp()});
 if(editMode==='news')await rdmDB.collection(RCOL.news).add({title:v('e1'),text:v('e2'),createdMs:now,updatedAt:rdmStamp()});
 if(editMode==='player'){const nums=(await rdmDB.collection(RCOL.players).get()).docs.map(d=>+String(d.id).replace(/\D/g,'')).filter(Number.isFinite),id='RDM'+String(Math.max(0,...nums)+1).padStart(3,'0');await rdmDB.collection(RCOL.players).doc(id).set({id,name:v('e1'),role:v('e2'),detail:v('e3'),image:img||'assets/logo.jpg',jersey:'',order:nums.length+1,active:true,updatedAt:rdmStamp()})}
 if(editMode==='honour')await rdmDB.collection(RCOL.honours).add({year:v('e1'),title:v('e2'),sub:v('e3'),image:img||'assets/logo.jpg',order:D.honours.length+1,createdMs:now,updatedAt:rdmStamp()});
 if(editMode==='gallery'){if(!img)return toast('ꜱᴇʟᴇᴄᴛ ᴀɴ ɪᴍᴀɢᴇ');await rdmDB.collection(RCOL.gallery).add({image:img,caption:v('e1')||'RDM MEMORY',createdMs:now,updatedAt:rdmStamp()})}
 if(editMode==='social')await rdmDB.collection(RCOL.socials).add({name:v('e1'),displayName:v('e4')||v('e1'),url:v('e2'),icon:v('e3')||'↗',image:img||'',order:D.socials.length+1,updatedAt:rdmStamp()});
 if(editMode==='editSocial')await rdmDB.collection(RCOL.socials).doc(editObj._docId).set({name:v('e1'),displayName:v('e4')||v('e1'),url:v('e2'),icon:v('e3')||editObj.icon||'↗',...(img?{image:img}:{}),updatedAt:rdmStamp()},{merge:true});
 if(editMode==='editPlayer'){const p=editObj;p.name=v('e1');p.role=v('e2');p.detail=v('e3');p.jersey=v('e4');p.nick=v('e5');p.bio=v('e6');if(img)p.image=img;await rdmDB.collection(RCOL.players).doc(p.id).set({name:p.name,role:p.role,detail:p.detail,jersey:p.jersey,...(img?{image:img}:{}),updatedAt:rdmStamp()},{merge:true});await rdmProfileWrite(p)}
 q('#editor').classList.remove('show');await rdmLoadAll();toast('ꜱᴀᴠᴇᴅ ᴏɴʟɪɴᴇ')}catch(e){console.error(e);toast(e.message==='IMAGE_TOO_LARGE'?'ɪᴍᴀɢᴇ ᴛᴏᴏ ʟᴀʀɢᴇ':'ꜱᴀᴠᴇ ꜰᴀɪʟᴇᴅ')}};
rdmRefresh();
