/* RDM V6.8.20 — in-page data forms. Browser prompt dialogs removed from cricket/admin workflows. */
(()=>{
const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function host(){let h=document.getElementById('rdmInlineFormHost');if(!h){h=document.createElement('section');h.id='rdmInlineFormHost';h.className='rdmInlineFormHost';document.querySelector('main')?.prepend(h)}return h}
function closeForm(){const h=host();h.innerHTML='';h.classList.remove('show')}
window.rdmCloseInlineForm=closeForm;
function field(f){const v=esc2(f.value??'');if(f.type==='textarea')return `<label>${f.label}<textarea name="${f.name}" rows="${f.rows||4}" ${f.required?'required':''}>${v}</textarea></label>`;if(f.type==='select')return `<label>${f.label}<select name="${f.name}">${(f.options||[]).map(o=>`<option ${String(o)===String(f.value)?'selected':''}>${esc2(o)}</option>`).join('')}</select></label>`;return `<label>${f.label}<input name="${f.name}" type="${f.type||'text'}" value="${v}" ${f.required?'required':''} ${f.placeholder?`placeholder="${esc2(f.placeholder)}"`:''}></label>`}
function openForm(title,fields,onSave){const h=host();h.innerHTML=`<div class="rdmInlineForm"><div class="rdmFormHead"><div><span>RDM CONTROL</span><h2>${esc2(title)}</h2></div><button type="button" class="rdmFormBack">← BACK</button></div><form>${fields.map(field).join('')}<div class="rdmFormActions"><button type="submit" class="primary">SAVE CHANGES</button><button type="button" class="secondary rdmCancel">CANCEL</button></div></form></div>`;h.classList.add('show');h.querySelector('.rdmFormBack').onclick=closeForm;h.querySelector('.rdmCancel').onclick=closeForm;h.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),d=Object.fromEntries(fd.entries());const b=e.submitter;b.disabled=true;try{await onSave(d);closeForm()}catch(err){console.error(err);toast?.('SAVE FAILED');b.disabled=false}};h.scrollIntoView({behavior:'smooth',block:'start'})}
const num=v=>Number(v||0)||0;
window.editStats=id=>{const s=(window.XD?.stats||XD?.stats||[]).find(z=>z.playerId===id)||{};openForm('EDIT PLAYER STATS',[['matches','MATCHES'],['runs','RUNS'],['wickets','WICKETS'],['highScore','HIGHEST SCORE'],['fours','FOURS'],['sixes','SIXES'],['fifties','50s'],['hundreds','100s'],['runOuts','RUN OUTS'],['strikeRate','STRIKE RATE'],['economy','ECONOMY']].map(([name,label])=>({name,label,type:'number',value:s[name]||0})).concat([{name:'bestBowling',label:'BEST BOWLING',value:s.bestBowling||''},{name:'last5',label:'LAST 5 MATCH FORM',value:s.last5||''},{name:'season',label:'SEASON / YEAR',value:s.season||'2027'}]),async d=>{await rdmDB.collection('PlayerStats').doc(id).set({...d,playerId:id,matches:num(d.matches),runs:num(d.runs),wickets:num(d.wickets),highScore:num(d.highScore),fours:num(d.fours),sixes:num(d.sixes),fifties:num(d.fifties),hundreds:num(d.hundreds),runOuts:num(d.runOuts),strikeRate:num(d.strikeRate),economy:num(d.economy),updatedAt:rdmStamp()},{merge:true});await xload()})};
window.addAchievement=()=>openForm('ADD ACHIEVEMENT',[{name:'title',label:'ACHIEVEMENT / AWARD',required:true},{name:'playerName',label:'PLAYER NAME',value:'TEAM'},{name:'detail',label:'DETAILS',type:'textarea'}],async d=>{await rdmDB.collection('Achievements').add({...d,createdMs:Date.now(),updatedAt:rdmStamp()});await xload()});
window.v6EditAchievement=id=>{const a=XD.achievements.find(x=>x._docId===id)||{};openForm('EDIT ACHIEVEMENT',[{name:'title',label:'ACHIEVEMENT / AWARD',value:a.title,required:true},{name:'playerName',label:'PLAYER NAME',value:a.playerName||'TEAM'},{name:'detail',label:'DETAILS',type:'textarea',value:a.detail||''}],async d=>{await rdmDB.collection('Achievements').doc(id).set({...d,updatedAt:rdmStamp()},{merge:true});await xload()})};
window.setAvailability=id=>{const a=XD.availability.find(z=>z.playerId===id)||{};openForm('PLAYER AVAILABILITY',[{name:'status',label:'STATUS',type:'select',value:a.status||'AVAILABLE',options:['AVAILABLE','UNAVAILABLE']}],async d=>{await rdmDB.collection('Availability').doc(id).set({playerId:id,status:d.status,updatedAt:rdmStamp()},{merge:true});await xload()})};
window.addLineup=()=>openForm('PUBLISH PLAYING XI',[{name:'title',label:'TITLE',value:'PLAYING XI'},{name:'match',label:'MATCH / OPPONENT'},{name:'players',label:'11 PLAYER IDs',type:'textarea',value:'RDM001,RDM002,RDM003,RDM004,RDM005,RDM006,RDM007,RDM008,RDM009,RDM010,RDM011'},{name:'subs',label:'SUBSTITUTE PLAYER IDs',value:'RDM012,RDM013,RDM014,RDM015'}],async d=>{await rdmDB.collection('PlayingXI').add({title:d.title,match:d.match,players:d.players.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,11),subs:d.subs.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),createdMs:Date.now(),updatedAt:rdmStamp()});await xload()});
window.addScorecard=()=>openForm('ADD SCORECARD',[{name:'opponent',label:'OPPONENT',required:true},{name:'date',label:'DATE'},{name:'venue',label:'VENUE'},{name:'ourScore',label:'RDM SCORE'},{name:'oppScore',label:'OPPONENT SCORE'},{name:'result',label:'RESULT'},{name:'potm',label:'PLAYER OF THE MATCH'}],async d=>{await rdmDB.collection('Matches').add({...d,note:d.result,status:'RESULT',createdMs:Date.now(),updatedAt:rdmStamp()});await rdmLoadAll()});
window.v6AddTournament=id=>{const x=(V6.tournaments||[]).find(z=>z._docId===id)||{};openForm(id?'EDIT TOURNAMENT':'ADD TOURNAMENT',[{name:'name',label:'TOURNAMENT NAME',value:x.name||'',required:true},{name:'season',label:'SEASON / YEAR',value:x.season||''},{name:'position',label:'FINAL POSITION / STATUS',value:x.position||''},{name:'fixtures',label:'FIXTURES / POINTS / NOTES',type:'textarea',value:x.fixtures||'',rows:6}],async d=>{d.updatedAt=rdmStamp();d.createdMs=x.createdMs||Date.now();id?await rdmDB.collection('Tournaments').doc(id).set(d,{merge:true}):await rdmDB.collection('Tournaments').add(d);await v6load()})};
window.v6AddOpponent=id=>{const x=(V6.opponents||[]).find(z=>z._docId===id)||{};openForm(id?'EDIT OPPONENT':'ADD OPPONENT',[{name:'name',label:'OPPONENT TEAM NAME',value:x.name||'',required:true},{name:'played',label:'MATCHES PLAYED',type:'number',value:x.played||0},{name:'won',label:'RDM WINS',type:'number',value:x.won||0},{name:'lost',label:'RDM LOSSES',type:'number',value:x.lost||0}],async d=>{d.played=num(d.played);d.won=num(d.won);d.lost=num(d.lost);d.updatedAt=rdmStamp();d.createdMs=x.createdMs||Date.now();id?await rdmDB.collection('Opponents').doc(id).set(d,{merge:true}):await rdmDB.collection('Opponents').add(d);await v6load()})};
window.v6AddRecord=id=>{const x=(V6.records||[]).find(z=>z._docId===id)||{};openForm(id?'EDIT RECORD':'ADD RECORD',[{name:'title',label:'RECORD TITLE',value:x.title||'',required:true},{name:'value',label:'RECORD VALUE',value:x.value||''},{name:'player',label:'PLAYER(S)',value:x.player||''},{name:'season',label:'SEASON / YEAR',value:x.season||new Date().getFullYear()}],async d=>{d.updatedAt=rdmStamp();d.createdMs=x.createdMs||Date.now();id?await rdmDB.collection('TeamRecords').doc(id).set(d,{merge:true}):await rdmDB.collection('TeamRecords').add(d);await v6load()})};
window.v6EditMatch=id=>{const m=D.matches.find(x=>x._docId===id)||{};openForm('EDIT MATCH SCORECARD',[{name:'tossWinner',label:'TOSS WINNER',value:m.tossWinner||''},{name:'tossDecision',label:'TOSS DECISION',value:m.tossDecision||''},{name:'batting',label:'BATTING SCORECARD',type:'textarea',value:m.batting||'',rows:6},{name:'bowling',label:'BOWLING SCORECARD',type:'textarea',value:m.bowling||'',rows:6},{name:'partnerships',label:'PARTNERSHIPS',type:'textarea',value:m.partnerships||''},{name:'fow',label:'FALL OF WICKETS',type:'textarea',value:m.fow||''},{name:'potm',label:'PLAYER OF THE MATCH',value:m.potm||''}],async d=>{await rdmDB.collection('Matches').doc(id).set({...d,updatedAt:rdmStamp()},{merge:true});await rdmLoadAll();setTimeout(v6render,100)})};
// Re-bind buttons that previously launched prompt chains.
setTimeout(()=>{const map={addAchievement:()=>addAchievement(),addLineup:()=>addLineup(),addTournament:()=>v6AddTournament(),addOpponent:()=>v6AddOpponent(),addScorecard:()=>addScorecard()};Object.entries(map).forEach(([id,fn])=>{const b=document.getElementById(id);if(b)b.onclick=fn})},500);
})();
