/* RDM V6.8.23 — final custom-form routing. Loaded LAST. No browser prompt for site data editing. */
(()=>{
 const n=v=>Number(v||0)||0, stamp=()=>typeof rdmStamp==='function'?rdmStamp():new Date().toISOString();
 const modal=(t,f,v,s)=>window.v62Modal(t,f,v||{},s);
 const get=(obj,key)=>{try{return obj?.[key]||[]}catch(e){return[]}};
 const stats=()=>get(window.XD||XD,'stats'), avails=()=>get(window.XD||XD,'availability'), opps=()=>get(window.V6||V6,'opponents'), tours=()=>get(window.V6||V6,'tournaments'), recs=()=>get(window.V6||V6,'records');
 const split=x=>String(x||'').split(',').map(v=>v.trim().toUpperCase()).filter(Boolean);
 window.editStats=id=>{if(!rdmAdmin())return;const s=stats().find(z=>z.playerId===id)||{};modal('EDIT PLAYER STATS',[{k:'matches',label:'MATCHES',type:'number'},{k:'runs',label:'RUNS',type:'number'},{k:'wickets',label:'WICKETS',type:'number'},{k:'highScore',label:'HIGHEST SCORE',type:'number'},{k:'bestBowling',label:'BEST BOWLING'},{k:'fours',label:'4s',type:'number'},{k:'sixes',label:'6s',type:'number'},{k:'fifties',label:'50s',type:'number'},{k:'hundreds',label:'100s',type:'number'},{k:'runOuts',label:'RUN OUTS',type:'number'},{k:'strikeRate',label:'STRIKE RATE',type:'number',step:'any'},{k:'economy',label:'ECONOMY',type:'number',step:'any'},{k:'last5',label:'LAST 5 FORM',full:true},{k:'season',label:'SEASON / YEAR'}],s,async d=>{['matches','runs','wickets','highScore','fours','sixes','fifties','hundreds','runOuts','strikeRate','economy'].forEach(k=>d[k]=n(d[k]));await rdmDB.collection('PlayerStats').doc(id).set({...d,playerId:id,updatedAt:stamp()},{merge:true});await xload();toast('STATS SAVED')})};
 window.v6AddOpponent=id=>{if(!rdmAdmin())return;const x=opps().find(z=>z._docId===id)||{};modal(id?'EDIT OPPONENT':'ADD OPPONENT',[{k:'name',label:'OPPONENT TEAM NAME',full:true},{k:'played',label:'MATCHES PLAYED',type:'number'},{k:'won',label:'RDM WINS',type:'number'},{k:'lost',label:'RDM LOSSES',type:'number'}],x,async d=>{if(!d.name){toast('TEAM NAME REQUIRED');throw Error('required')}['played','won','lost'].forEach(k=>d[k]=n(d[k]));const ref=id?rdmDB.collection('Opponents').doc(id):rdmDB.collection('Opponents').doc();await ref.set({...d,createdMs:x.createdMs||Date.now(),updatedAt:stamp()},{merge:true});await v6load();toast('OPPONENT SAVED')})};
 window.v6AddTournament=id=>{if(!rdmAdmin())return;const x=tours().find(z=>z._docId===id)||{};modal(id?'EDIT TOURNAMENT':'ADD TOURNAMENT',[{k:'name',label:'TOURNAMENT NAME',full:true},{k:'season',label:'SEASON / YEAR'},{k:'status',label:'STATUS',type:'select',options:['UPCOMING','ONGOING','COMPLETED']},{k:'position',label:'RDM POSITION'},{k:'venue',label:'VENUE'},{k:'dates',label:'DATES'},{k:'organizer',label:'ORGANIZER'},{k:'teams',label:'TOTAL TEAMS',type:'number'},{k:'matches',label:'RDM MATCHES',type:'number'},{k:'wins',label:'RDM WINS',type:'number'},{k:'losses',label:'RDM LOSSES',type:'number'},{k:'fixtures',label:'FIXTURES / POINTS / NOTES',type:'textarea',full:true}],x,async d=>{if(!d.name){toast('NAME REQUIRED');throw Error('required')}const ref=id?rdmDB.collection('Tournaments').doc(id):rdmDB.collection('Tournaments').doc();await ref.set({...d,createdMs:x.createdMs||Date.now(),updatedAt:stamp()},{merge:true});await v6load();toast('TOURNAMENT SAVED')})};
 window.addLineup=()=>{if(!rdmAdmin())return;modal('PUBLISH PLAYING XI',[{k:'title',label:'TITLE'},{k:'match',label:'MATCH / OPPONENT'},{k:'players',label:'11 PLAYER IDs • COMMA SEPARATED',type:'textarea',full:true},{k:'subs',label:'SUBSTITUTE PLAYER IDs',type:'textarea',full:true}],{title:'PLAYING XI',players:'RDM001,RDM002,RDM003,RDM004,RDM005,RDM006,RDM007,RDM008,RDM009,RDM010,RDM011',subs:'RDM012,RDM013,RDM014,RDM015'},async d=>{await rdmDB.collection('PlayingXI').add({title:d.title||'PLAYING XI',match:d.match,players:split(d.players).slice(0,11),subs:split(d.subs),createdMs:Date.now(),updatedAt:stamp()});await xload();toast('PLAYING XI PUBLISHED')})};
 window.setAvailability=id=>{const ok=rdmAdmin()||(window.session?.mode==='player'&&session.playerId===id);if(!ok)return;const a=avails().find(z=>z.playerId===id)||{};modal('PLAYER AVAILABILITY',[{k:'status',label:'STATUS',type:'select',options:['AVAILABLE','UNAVAILABLE']}],{status:a.status||'AVAILABLE'},async d=>{await rdmDB.collection('Availability').doc(id).set({playerId:id,status:d.status,updatedAt:stamp()},{merge:true});await xload();toast('STATUS SAVED')})};
 window.addScorecard=()=>{if(!rdmAdmin())return;modal('ADD SCORECARD / RESULT',[{k:'opponent',label:'OPPONENT',full:true},{k:'date',label:'DATE',type:'date'},{k:'venue',label:'VENUE'},{k:'ourScore',label:'RDM SCORE'},{k:'oppScore',label:'OPPONENT SCORE'},{k:'result',label:'RESULT',full:true},{k:'potm',label:'PLAYER OF THE MATCH',full:true}],{},async d=>{if(!d.opponent){toast('OPPONENT REQUIRED');throw Error('required')}await rdmDB.collection('Matches').add({...d,note:d.result,status:'RESULT',createdMs:Date.now(),updatedAt:stamp()});await rdmLoadAll();toast('SCORECARD SAVED')})};
 window.addAchievement=()=>{if(!rdmAdmin())return;modal('ADD ACHIEVEMENT',[{k:'title',label:'AWARD / ACHIEVEMENT',full:true},{k:'playerName',label:'PLAYER NAME / TEAM'},{k:'detail',label:'DETAILS',type:'textarea',full:true}],{playerName:'TEAM'},async d=>{if(!d.title){toast('TITLE REQUIRED');throw Error('required')}await rdmDB.collection('Achievements').add({...d,createdMs:Date.now(),updatedAt:stamp()});await xload();toast('ACHIEVEMENT SAVED')})};
 window.v6EditAchievement=id=>{if(!rdmAdmin())return;const a=get(window.XD||XD,'achievements').find(x=>x._docId===id);if(!a)return;modal('EDIT ACHIEVEMENT',[{k:'title',label:'AWARD / ACHIEVEMENT',full:true},{k:'playerName',label:'PLAYER NAME / TEAM'},{k:'detail',label:'DETAILS',type:'textarea',full:true}],a,async d=>{await rdmDB.collection('Achievements').doc(id).set({...d,updatedAt:stamp()},{merge:true});await xload();toast('ACHIEVEMENT SAVED')})};
 window.v6AddRecord=id=>{if(!rdmAdmin())return;const x=recs().find(z=>z._docId===id)||{};modal(id?'EDIT TEAM RECORD':'ADD TEAM RECORD',[{k:'title',label:'RECORD TITLE',full:true},{k:'value',label:'RECORD VALUE'},{k:'player',label:'PLAYER(S) • OPTIONAL'},{k:'season',label:'SEASON / YEAR'}],x,async d=>{if(!d.title){toast('TITLE REQUIRED');throw Error('required')}const ref=id?rdmDB.collection('TeamRecords').doc(id):rdmDB.collection('TeamRecords').doc();await ref.set({...d,createdMs:x.createdMs||Date.now(),updatedAt:stamp()},{merge:true});await v6load();toast('RECORD SAVED')})};
 window.v6EditMatch=id=>{if(!rdmAdmin())return;const m=(window.D?.matches||D.matches||[]).find(x=>x._docId===id);if(!m)return;modal('EDIT FULL SCORECARD',[{k:'tossWinner',label:'TOSS WINNER'},{k:'tossDecision',label:'TOSS DECISION',type:'select',options:['BAT','BOWL']},{k:'batting',label:'BATTING SCORECARD',type:'textarea',full:true},{k:'bowling',label:'BOWLING SCORECARD',type:'textarea',full:true},{k:'partnerships',label:'PARTNERSHIPS',type:'textarea',full:true},{k:'fow',label:'FALL OF WICKETS',type:'textarea',full:true},{k:'potm',label:'PLAYER OF THE MATCH',full:true}],m,async d=>{await rdmDB.collection('Matches').doc(id).set({...d,updatedAt:stamp()},{merge:true});await rdmLoadAll();setTimeout(()=>window.v6render?.(),100);toast('MATCH UPDATED')})};
 // Route dynamic buttons in capture phase so old prompt listeners never run.
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;let f=null;if(b.id==='addOpponent')f=()=>window.v6AddOpponent();else if(b.id==='addTournament')f=()=>window.v6AddTournament();else if(b.id==='addLineup')f=window.addLineup;else if(b.id==='addScorecard')f=window.addScorecard;else if(b.id==='addAchievement')f=window.addAchievement;if(f){e.preventDefault();e.stopImmediatePropagation();f()}},true);
})();
