/* RDM V6.8.22 — unified custom popup forms (no browser prompt for cricket data actions) */
(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>Number(v||0)||0, stamp=()=>typeof rdmStamp==='function'?rdmStamp():new Date().toISOString();
 function close(){document.getElementById('rdmProFormModal')?.remove();}
 window.rdmCloseProForm=close;
 window.v62Modal=function(title,fields,values={},onSave){
   close(); const wrap=document.createElement('div'); wrap.id='rdmProFormModal'; wrap.className='rdmProFormModal';
   const controls=fields.map(f=>{const val=values[f.k]??'';let ctl='';
     if(f.type==='textarea') ctl=`<textarea data-k="${f.k}" placeholder="${esc(f.ph||'')}">${esc(val)}</textarea>`;
     else if(f.type==='select') ctl=`<select data-k="${f.k}">${(f.options||[]).map(o=>`<option value="${esc(o)}" ${String(val)===String(o)?'selected':''}>${esc(o)}</option>`).join('')}</select>`;
     else ctl=`<input data-k="${f.k}" type="${f.type||'text'}" value="${esc(val)}" placeholder="${esc(f.ph||'')}">`;
     return `<label class="${f.full?'full':''}"><span>${f.label}</span>${ctl}</label>`;
   }).join('');
   wrap.innerHTML=`<section class="rdmProFormCard" role="dialog" aria-modal="true"><button class="rdmProClose" type="button" aria-label="Close">×</button><form><div class="rdmProGrid">${controls}</div><button class="rdmProSave" type="submit">SAVE</button></form></section>`;
   document.body.appendChild(wrap); document.body.classList.add('rdmFormOpen');
   const finish=()=>{close();document.body.classList.remove('rdmFormOpen')};
   wrap.querySelector('.rdmProClose').onclick=finish;
   wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();const d={};wrap.querySelectorAll('[data-k]').forEach(x=>d[x.dataset.k]=x.value.trim());const btn=wrap.querySelector('.rdmProSave');btn.disabled=true;btn.textContent='SAVING...';try{await onSave(d);finish()}catch(err){console.error(err);btn.disabled=false;btn.textContent='SAVE'}};
 };
 function statsData(){try{return XD.stats||[]}catch(e){return[]}} function availData(){try{return XD.availability||[]}catch(e){return[]}}
 function opponents(){try{return V6.opponents||[]}catch(e){return[]}} function tournaments(){try{return V6.tournaments||[]}catch(e){return[]}}
 window.rdmFormStats=function(id){if(!rdmAdmin())return;const s=statsData().find(z=>z.playerId===id)||{};v62Modal('EDIT PLAYER STATS',[{k:'matches',label:'MATCHES',type:'number'},{k:'runs',label:'RUNS',type:'number'},{k:'wickets',label:'WICKETS',type:'number'},{k:'highScore',label:'HIGHEST SCORE',type:'number'},{k:'bestBowling',label:'BEST BOWLING'},{k:'fours',label:'4s',type:'number'},{k:'sixes',label:'6s',type:'number'},{k:'fifties',label:'50s',type:'number'},{k:'hundreds',label:'100s',type:'number'},{k:'runOuts',label:'RUN OUTS',type:'number'},{k:'strikeRate',label:'STRIKE RATE',type:'number'},{k:'economy',label:'ECONOMY',type:'number'}],s,async d=>{Object.keys(d).forEach(k=>{if(k!=='bestBowling')d[k]=num(d[k])});await rdmDB.collection('PlayerStats').doc(id).set({...d,playerId:id,updatedAt:stamp()},{merge:true});await xload();toast('STATS SAVED')})};
 window.rdmFormOpponent=function(id){if(!rdmAdmin())return;const x=opponents().find(z=>z._docId===id)||{};v62Modal(id?'EDIT OPPONENT':'ADD OPPONENT',[{k:'name',label:'OPPONENT TEAM NAME',full:true},{k:'played',label:'MATCHES PLAYED',type:'number'},{k:'won',label:'RDM WINS',type:'number'},{k:'lost',label:'RDM LOSSES',type:'number'}],x,async d=>{if(!d.name){toast('TEAM NAME REQUIRED');throw Error('required')}['played','won','lost'].forEach(k=>d[k]=num(d[k]));const ref=id?rdmDB.collection('Opponents').doc(id):rdmDB.collection('Opponents').doc();await ref.set({...d,createdMs:x.createdMs||Date.now(),updatedAt:stamp()},{merge:true});await v6load();toast('OPPONENT SAVED')})};
 window.rdmFormTournament=function(id){if(!rdmAdmin())return;const x=tournaments().find(z=>z._docId===id)||{};v62Modal(id?'EDIT TOURNAMENT':'ADD TOURNAMENT',[{k:'name',label:'TOURNAMENT NAME',full:true},{k:'season',label:'SEASON / YEAR'},{k:'status',label:'STATUS',type:'select',options:['UPCOMING','ONGOING','COMPLETED']},{k:'position',label:'RDM POSITION'},{k:'venue',label:'VENUE'},{k:'dates',label:'DATES'},{k:'organizer',label:'ORGANIZER'},{k:'teams',label:'TOTAL TEAMS',type:'number'},{k:'matches',label:'RDM MATCHES',type:'number'},{k:'wins',label:'RDM WINS',type:'number'},{k:'losses',label:'RDM LOSSES',type:'number'},{k:'fixtures',label:'FIXTURES / POINTS / NOTES',type:'textarea',full:true}],x,async d=>{if(!d.name){toast('NAME REQUIRED');throw Error('required')}const ref=id?rdmDB.collection('Tournaments').doc(id):rdmDB.collection('Tournaments').doc();await ref.set({...d,createdMs:x.createdMs||Date.now(),updatedAt:stamp()},{merge:true});await v6load();toast('TOURNAMENT SAVED')})};
 window.rdmFormLineup=function(){if(!rdmAdmin())return;v62Modal('PUBLISH PLAYING XI',[{k:'title',label:'TITLE'},{k:'match',label:'MATCH / OPPONENT'},{k:'players',label:'11 PLAYER IDs • COMMA SEPARATED',type:'textarea',full:true},{k:'subs',label:'SUBSTITUTE PLAYER IDs',type:'textarea',full:true}],{title:'PLAYING XI',players:'RDM001,RDM002,RDM003,RDM004,RDM005,RDM006,RDM007,RDM008,RDM009,RDM010,RDM011',subs:'RDM012,RDM013,RDM014,RDM015'},async d=>{const split=x=>String(x||'').split(',').map(v=>v.trim().toUpperCase()).filter(Boolean);await rdmDB.collection('PlayingXI').add({title:d.title,match:d.match,players:split(d.players).slice(0,11),subs:split(d.subs),createdMs:Date.now(),updatedAt:stamp()});await xload();toast('PLAYING XI PUBLISHED')})};
 window.rdmFormAvailability=function(id){const ok=rdmAdmin()||(window.session?.mode==='player'&&session.playerId===id);if(!ok)return;const a=availData().find(z=>z.playerId===id)||{};v62Modal('PLAYER AVAILABILITY',[{k:'status',label:'STATUS',type:'select',options:['AVAILABLE','UNAVAILABLE']}],{status:a.status||'AVAILABLE'},async d=>{await rdmDB.collection('Availability').doc(id).set({playerId:id,status:d.status,updatedAt:stamp()},{merge:true});await xload();toast('STATUS SAVED')})};
 window.rdmFormScorecard=function(){if(!rdmAdmin())return;v62Modal('ADD SCORECARD / RESULT',[{k:'opponent',label:'OPPONENT',full:true},{k:'date',label:'DATE',type:'date'},{k:'venue',label:'VENUE'},{k:'ourScore',label:'RDM SCORE'},{k:'oppScore',label:'OPPONENT SCORE'},{k:'result',label:'RESULT',full:true},{k:'potm',label:'PLAYER OF THE MATCH',full:true}],{},async d=>{if(!d.opponent){toast('OPPONENT REQUIRED');throw Error('required')}await rdmDB.collection('Matches').add({...d,note:d.result,status:'RESULT',createdMs:Date.now(),updatedAt:stamp()});await rdmLoadAll();toast('SCORECARD SAVED')})};
 window.editStats=window.rdmFormStats; window.v6AddOpponent=window.rdmFormOpponent; window.v6AddTournament=window.rdmFormTournament; window.addLineup=window.rdmFormLineup; window.setAvailability=window.rdmFormAvailability; window.addScorecard=window.rdmFormScorecard;
 // Capture buttons before older listeners can open browser prompts.
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;let fn=null;if(b.id==='addOpponent')fn=()=>rdmFormOpponent();else if(b.id==='addTournament')fn=()=>rdmFormTournament();else if(b.id==='addLineup')fn=rdmFormLineup;else if(b.id==='addScorecard')fn=rdmFormScorecard;if(fn){e.preventDefault();e.stopImmediatePropagation();fn()}},true);
})();
